### ISSUE TITLE
reporting to trial 565 fails with a 505

### ISSUE THREAD

**Issue by drcjar** [openhealthcare/randomise.me#236]
reported by @bengoldacre reproduced by me
http://randomizeme.org/trials/565

**Comment by davidmiller** [comment]
Relevant server error log reveals : 

``` python
Traceback (most recent call last):

  File "/home/app/randomise_me/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/home/app/randomise_me/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)

  File "/home/app/randomise_me/local/lib/python2.7/site-packages/django/views/generic/base.py", line 86, in dispatch
    return handler(request, *args, **kwargs)

  File "/home/app/randomise_me/rm/trials/views/__init__.py", line 146, in post
    if not self.request.POST.get('minutes') and self.request.get('seconds'):

AttributeError: 'WSGIRequest' object has no attribute 'get'
```
